# Generated by Django 4.1.1 on 2022-09-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'author')},
        ),
    ]
