# Generated by Django 4.1.1 on 2022-09-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('slug', 'author')},
        ),
    ]
